config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: :sessions,
                                    registrations: :registrations }
  resources :user_stocks, except: [:show, :edit, :update]
  resources :users, only: [:show]
  resources :friendships
  get 'my_friends', to: 'users#my_friends'
  get 'my_portfolio', to: 'users#my_portfolio' 
  get 'search_stocks', to: 'stocks#search'
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'
  root 'welcome#index'
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
# ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  validates_presence_of :user, :friend
  validates_uniqueness_of :user_id, scope: :friend_id
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
# Methods for stocks
class Stock < ApplicationRecord
  validates_presence_of :ticker, :name, :last_price
  validates_uniqueness_of :ticker
  has_many :user_stocks
  has_many :users, through: :user_stocks
  class << self
    def find_by_ticker(ticker)
      find_by(ticker: ticker)
    end

    def new_from_lookup(ticker)
      stock = StockQuote::Stock.quote(ticker) rescue nil
      correct?(stock) && new(ticker: stock.symbol,
                             name: stock.name,
                             last_price: price(stock))
    end

    def price(stock)
      eod_price(stock) || open_price(stock)
    end

    def correct?(stock)
      stock.is_a?(StockQuote::Stock) &&
        stock.symbol &&
        !stock.symbol.empty?
    end

    def eod_price(stock)
      eod_price = stock.eo
      eod_price && !eod_price.empty? && eod_price.to_f
    end

    def open_price(stock)
      open_price = stock.op
      return 0 if open_price.blank?
      open_price.delete(',').to_f
    end
  end
end

app/models/user.rb
# User model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  EMAIL_MATCHER = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :first_name, length: { maximum: 20 }
  validates :last_name, length: { maximum: 20 }
  validates :email, presence: true,
                    length: { maximum: 45 },
                    uniqueness: true,
                    format: { with: EMAIL_MATCHER,
                              message: 'Invalid email' }
  has_many :user_stocks, dependent: :destroy
  has_many :stocks, through: :user_stocks
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  def self.demo
    user = User.offset(rand(User.count)).limit(1).first
    user.update(password: 'fintrack')
    user
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    'Anonymous'
  end

  def can_add_stock?(ticker)
    under_stock_limit? && !stock_already_added?(ticker)
  end

  def under_stock_limit?
    user_stocks.count < 10
  end

  def stock_already_added?(ticker)
    stock = Stock.find_by_ticker(ticker)
    stock && user_stocks.where(stock_id: stock.id).any?
  end

  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end

  def except_current_user(users)
    users.reject { |user| user.id == id }
  end

  def self.search(param)
    return User.none if param.blank?
    param.strip!
    param.downcase!
    (first_name_matches(param) +
      last_name_matches(param) +
      email_matches(param)).uniq
  end

  def self.first_name_matches(param)
    where("lower(first_name) like ?", "%#{param}%")
  end

  def self.last_name_matches(param)
    where("lower(last_name) like ?", "%#{param}%")
  end

  def self.email_matches(param)
    where("lower(email) like ?", "%#{param}%")
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  validates_presence_of :user, :stock
  validates_uniqueness_of :user_id, scope: :stock_id
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
# ApplicationController
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index]
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[first_name last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    @friendship = current_user.friendships.find_by(friend_id: params[:id])
    @friendship.destroy
    respond_to do |format|
      format.html do
        redirect_to my_friends_path,
                    notice: 'Friend was successfully removed'
      end
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def after_sign_up_path_for(_resource)
    my_portfolio_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    redirect_to my_portfolio_path
  end
end

app/controllers/stocks_controller.rb
# StocksController
class StocksController < ApplicationController
  def search
    if params[:stock]
      @stock = Stock.find_by_ticker(params[:stock]) ||
               Stock.new_from_lookup(params[:stock])
    end
    respond_to do |format|
      format.js { render 'search.js.erb.coffee' }
      format.html { render 'users/my_portfolio' }
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    new_by_stock
    respond_to do |format|
      format.html do
        redirect_to_portfolio(@user_stock.save)
      end
    end
  end

  def destroy
    @user_stock = UserStock.find(params[:id])
    @user_stock.destroy
    respond_to do |format|
      format.html do
        redirect_to my_portfolio_path,
                    notice: 'Stock was successfully removed from portfolio.'
      end
      format.json { head :no_content }
    end
  end

  private

  def new_by_stock
    if params[:stock_id].present?
      @user_stock = UserStock.new(stock_id: params[:stock_id],
                                  user: current_user)
    else
      new_by_ticker
    end
  end

  def new_by_ticker
    stock = Stock.find_by_ticker(params[:stock_ticker])
    if stock
      @user_stock = UserStock.new(stock: stock, user: current_user)
    else
      new_by_lookup
    end
  end

  def new_by_lookup
    stock = Stock.new_from_lookup(params[:stock_ticker])
    attr = stock && stock.save ? { stock: stock, user: current_user } : {}
    @user_stock = UserStock.new(attr)
  end

  def redirect_to_portfolio(saved)
    if saved
      ticker = @user_stock.stock.ticker
      message = { notice: "Stock #{ticker} was successfully added" }
    else
      message = { error: 'Stock cannot be created' }
    end
    redirect_to my_portfolio_path, message
  end
end

app/controllers/users_controller.rb
# UsersController
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @user_stocks = user_stocks_with_details
  end

  def my_friends
    @friends = current_user.friends
  end

  def search
    @users = User.search(params[:search_param])
    @users = current_user.except_current_user(@users) if @users.any?
    respond_to do |format|
      format.js { render 'search.js.erb.coffee' }
      format.html { render :my_portfolio }
    end
  end

  def add_friend
    @friend = User.find(params[:friend])
    current_user.friends << @friend
    redirect_to my_friends_path, notice: 'Friend was successfully added.'
  end

  def show
    @user = User.find(params[:id])
    @user_stocks = user_stocks_with_details
  end

  private

  def user_stocks_with_details
    User.includes(:stocks).find(current_user.id).user_stocks
  end
end

app/controllers/welcome_controller.rb
# WelcomeController
class WelcomeController < ApplicationController
  def index; end
end

app/views/friends/_lookup.html.slim
#friend-lookup
  h3 Search for Friends
  = form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do
    .form-group.row.no-padding.test-center.col-md-12
      .col-xs-10
        = text_field_tag :search_param,
                         params[:search_param],
                         placeholder: 'First name, last name or email',
                         autofocus: true,
                         class: 'form-control search-box input-lg'
      .col-xs-2
        = button_tag type: :submit, class: 'btn btn-lg btn-success', id: 'btn-lookup' do
          i.fa.fa-search 
  = render 'shared/spinner' 
  - unless @users.blank?
    #friend-lookup-results.well.results-block.col-md-10
      table.search-result-table.col-md-12
        tbody
          = render partial: 'friends/user', collection: @users
  
  #lookup-errors.col-md-12.text-warning
    #friend-lookup-errors

app/views/friends/_user.html.slim
tr
  td
    p
      strong
        = user.full_name
    p
      = user.email
  td
    - if current_user.not_friends_with?(user)
      = link_to 'View Profile', user_path(user),
                                class: 'btn btn-primary btn-xs action'
      = link_to 'Add friend',
        add_friend_path(user: current_user, friend: user),
        class: 'btn btn-xs btn-success action',
        method: :post
    - else
      span.label.label-default.action
        'Your friend

app/views/friends/search.js.erb
$('#friend-lookup').replaceWith("<%= escape_javascript(render 'lookup') %>");
$('#friend-lookup-errors').replaceWith("<%= @friend ? '' : 'User was not found.' %>");
init_friend_lookup();

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    noscript
      meta http-equiv="refresh" content="2;url=http://yoursite.com/nojswarning.html"
    title= content_for?(:title) ? yield(:title) : "Fintrack"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    //#= favicon_link_tag asset_path('apple-touch-icon-precomposed.png'), :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    //#= favicon_link_tag asset_path('favicon.ico'), :rel => 'shortcut icon'
    = javascript_include_tag "application"
    //<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    = javascript_include_tag "https://use.fontawesome.com/releases/v5.0.6/js/all.js"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    = render 'shared/navigation'
    p#javascript_require
      'No javascript, please enable JavaScript in order to use this website
    #main.container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield

      = render 'shared/footer'

app/views/shared/_footer.html.slim
footer
  p &copy; Company 2018

app/views/shared/_navigation.html.slim
.navbar.navbar-default.navbar-static-top
  .container
    = link_to 'Finance Tracker', root_path, class: 'navbar-brand'
    - if current_user
      button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
        span.icon-bar
        span.icon-bar
        span.icon-bar
      .navbar-collapse.collapse.navbar-responsive-collapse
        ul.nav.navbar-nav
          li = link_to 'My Portfolio', my_portfolio_path
          li = link_to 'My Friends', my_friends_path
          li = link_to 'My Profile', edit_registration_path(current_user)
        ul.nav.navbar-nav.navbar-right.col-sm-4
          li.col-sm-4.col-sm-push-8.logout
            = link_to 'Logout', destroy_user_session_path, method: :delete
          li.col-sm-8.col-sm-pull-4.user-name.text-right
            i.fa.fa-user
            span.current-user
              = current_user.full_name.present? ? current_user.full_name : current_user.email
    - else
      ul.nav.navbar-nav.navbar-right.col-sm-4
        li.col-sm-4.col-sm-push-8.logout
          = link_to 'Login', new_user_session_path
          

app/views/shared/_spinner.html.slim
#spinner.row.col-md-12.text-center.spinner
  i.fa.fa-spinner.fa-spin.fa-2x
  span.spinner-message
    'Processing...
  

app/views/stocks/_list.html.slim
table.table.table-triped
  thead
    tr
        th.page-header(colspan='4')
          h3
            - if controller.action_name == 'my_portfolio' 
              'My Portfolio
            -else
               'Portfolio
    tr
      th Name
      th Symbol
      th Current Price
      - if @user.id == current_user.id
        th Actions
  tbody
    = render partial: 'stocks/user_stock', collection: @user_stocks

app/views/stocks/_lookup.html.slim
#stock-lookup
  h3 Search for Stocks
  = form_tag search_stocks_path, remote: true, method: :get, id: 'stock-lookup-form' do
    .form-group.row.no-padding.test-center.col-md-12
      .col-xs-10
        = text_field_tag :stock, params[:stock], placeholder: 'Stock ticker symbol',
                         autofocus: true, class: 'form-control search-box input-lg'
      .col-xs-2
        = button_tag type: :submit, class: 'btn btn-lg btn-success', id: 'btn-lookup' do
          i.fa.fa-search 
  = render 'shared/spinner' 
  - if @stock
    #stock-lookup-results.well.results-block.col-sm-10
      table.search-result-table.col-md-12
        tbody
          tr
            td
              = @stock.ticker
            td
              strong
                = @stock.name
            td
              = @stock.last_price
            td
              - if current_user.can_add_stock?(@stock.ticker)
                = link_to 'Add to my Stocks', user_stocks_path(user:current_user,
                                              stock_ticker: @stock.ticker,
                                              stock_id: @stock.id || ''),
                                              class: 'btn btn-xs btn-success action',
                                              method: :post
              - else
                span.label.label-default.action
                  'Stock 
                  - unless current_user.under_stock_limit?
                    'limit exceeded
                  - if current_user.stock_already_added?(@stock.ticker)
                    'is added already
  #lookup-errors.col-md-12.text-warning
    #stock-lookup-errors

app/views/stocks/_news.html.slim
.row
  .col-xs-12
    h5
      em
        span#messages 
          'Hot News: soon

app/views/stocks/_user_stock.html.slim
tr
  td
    strong 
      = user_stock.stock.name
  td = user_stock.stock.ticker
  td 
    span(id="price-for-#{user_stock.stock.id}") 
      = user_stock.stock.last_price
    - if @user.id == current_user.id
      td
        = link_to 'Delete', user_stock_path(user_stock),
                            method: :delete,
                            data: { confirm: 'Are you sure?' },
                            class: 'btn btn-sm btn-danger action'

app/views/users/_friend.html.slim
tr
  td 
    strong
      = friend.full_name
  td = friend.email.truncate(30)
  td
    = link_to 'View Profile', user_path(friend),
                              class: 'btn btn-primary btn-sm action' 
    = link_to 'Remove Friend', friendship_path(friend),
                               method: :delete,
                               data: { confirm: 'Are you sure?' },
                               class: 'btn btn-sm btn-danger action'

app/views/users/my_friends.html.slim
= render 'friends/lookup'
- if @friends.any?
  table.table.table-triped
    thead
      tr
        th.page-header(colspan='3')
          h3 My Friends
      tr
        th Name
        th Email
        th Actions
    tbody
      = render partial: 'users/friend', collection: @friends
- else
  .row.col-sm-12
    p.lead 
      'You don't have any friends yet. Please add some! 

app/views/users/my_portfolio.html.slim
= render 'stocks/lookup'
= render 'stocks/news'
= render 'stocks/list'

app/views/users/show.html.slim
h3 User Details
dl.dl-horizontal
  dt
    'Full Name:
  dd = @user.full_name
  dt
    'Email:
  dd = @user.email
  
- if @user.stocks.any?
  = render 'stocks/list'
- else
  p.lead This user is not tracking any stocks
  
= link_to 'Back', my_friends_path, class: 'btn btn-primary'

app/views/welcome/index.html.slim
h3 Welcome to Finance Tracker
div.welcome-message
  h5 You can manage your stocks here
  h5 Please use My Portfolio in order to add tickers needed
  
div.welcome-message
  p For demo mode, please use next credentials:
        
  dl.dl-horizontal.bg-info
    dt
      'Login Name:
    dd = User.demo.email
    dt
      'Password:
    dd fintrack
      
div.welcome-message
  p
    'Or you can register new user if prefer